// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { storageAdapter } from '@/lib/storageAdapter';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const USE_LOCAL_STORAGE = import.meta.env.VITE_USE_LOCAL_STORAGE === 'true';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create real Supabase client
const realSupabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Export either real Supabase client or localStorage adapter based on environment
export const supabase = USE_LOCAL_STORAGE ? storageAdapter : realSupabase;

// Debug logging
if (USE_LOCAL_STORAGE) {
  console.log('🚀 localStorage mode is ACTIVE - using localStorage adapter');
} else {
  console.log('🔗 Supabase mode is ACTIVE - using real Supabase client');
}